import './globals.css';
import {Inter} from 'next/font/google';
import Providers from "@/utils/providers";

const inter = Inter({subsets: ['latin']})

export const metadata = {
  title: 'Document Verify',
  description: 'Generated by create next app',
}


export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
};
